name: Build Android and iOS
on:
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleDebug -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.SAMPLE_SECRET }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.SAMPLE_SECRET }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/
  build-ios:
    needs: install-and-test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gpg
        run: brew install gnupg
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          rm -rf ios/build
          rm -rf ios/Pods ios/Podfile.lock
          cd ios && pod install
      - name: Setup provisioning profile
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Build app
        run: |
          cd ios && xcodebuild archive \
            -workspace loginApp.xcworkspace \
            -scheme loginApp \
            -configuration Release \
            -archivePath $PWD/build/loginApp.xcarchive \
            IPHONEOS_DEPLOYMENT_TARGET=9.0
            "OTHER_CODE_SIGN_FLAGS=--keychain '~/Library/Keychains/build.keychain'"
      - name: Export app
        run: |
          cd ios && xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/loginApp.xcarchive \
            -exportOptionsPlist $PWD/loginApp/iosExportOptions.plist \
            -exportPath $PWD/build
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: loginApp.ipa
          path: ios/build/
