name: Build Android and iOS
on:
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleDebug -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.SAMPLE_SECRET }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.SAMPLE_SECRET }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/
  build-ios:
    needs: install-and-test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |
          xcodebuild -workspace ./loginApp.xcworkspace -scheme loginApp archive -archivePath ./loginApp.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./loginApp.xcarchive -exportPath . -exportOptionsPlist ./loginApp/Info.plist
          mv loginApp.ipa ./../loginApp.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: loginAppp.ipa
          path: ios/build/
